language: cpp

git:
  submodules: true

compiler:
  - gcc

os:
  - windows

env:
  global:
    PYTHONPATH: ${TRAVIS_BUILD_DIR}/build/
    PY_CMD: /c/Python38/python.exe
    PATH: /c/ProgramData/chocolatey/bin:/c/Python38:/c/Python38/Scripts:$PATH
    MK_CMD: mingw32-make
    PY_EXE_PATH: ${PY_CMD}
    PY_LIB_PATH: /c/Python38/python38.dll
    PY_INC_PATH: /c/Python38/include

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  #- curl -L https://github.com/lucasg/Dependencies/releases/download/v1.10/Dependencies_x64_Release.zip --output dependencies.zip
  #- mkdir deps
  #- cd deps
  #- unzip ../dependencies.zip
  #- cd ..
  - choco install python

install:
  - $PY_CMD -m pip install --user --upgrade pip wheel setuptools
  - $PY_CMD -m pip install --user pytest

script:
  - export CMAKE_GENERATOR="MinGW Makefiles"
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - echo $CMAKE_GENERATOR
  - echo cmake -DPYTHON_EXECUTABLE=${PY_EXE_PATH} -DPYTHON_LIBRARY=${PY_LIB_PATH} -DPYTHON_INCLUDE_DIR=${PY_INC_PATH} ..
  - cmake -DCMAKE_MAKE_PROGRAM=${MK_CMD} -DPYTHON_EXECUTABLE=${PY_EXE_PATH} -DPYTHON_LIBRARY=${PY_LIB_PATH} -DPYTHON_INCLUDE_DIR=${PY_INC_PATH} ..
  - ${MK_CMD} -j4
  - cd ${TRAVIS_BUILD_DIR}
  - cp /c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/libgcc_s_seh-1.dll ${PYTHONPATH}
  - cp /c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/libstdc++-6.dll ${PYTHONPATH}
  - $PY_CMD -m pytest ./test_bindings.py
